apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
       - name: nginx-container
         image: nginx 
         resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
         ports:
          - containerPort: 80
         volumeMounts:
           - name: html-vol
             mountPath: /usr/share/nginx/html
     volumes:
        - name: html-vol
          persistentVolumeClaim:
            claimName: nginx-pvc